/* ============================================
   KarigarAI - Localization Module
   ============================================ */

const I18N = {
    currentLang: 'en',

    translations: {
        en: {
            // Common
            appName: 'KarigarAI',
            tagline: 'Your AI-powered business manager',
            loading: 'Loading...',
            save: 'Save',
            cancel: 'Cancel',
            delete: 'Delete',
            edit: 'Edit',
            back: 'Back',
            next: 'Next',
            done: 'Done',
            close: 'Close',
            search: 'Search...',
            viewAll: 'View All',
            startSelling: 'Start Selling',
            seeHowItWorks: 'See How It Works',
            continue_: 'Continue',
            continueAsDemo: 'Continue as Demo Artisan',

            // Landing
            landingTitle: 'Turn your craft into a digital business',
            landingSubtitle: 'KarigarAI helps artisans create professional product listings, discover the right price, and reach buyers online.',
            workflowPhoto: 'Product Photo',
            workflowAI: 'AI Enhancement',
            workflowListing: 'AI Listing',
            workflowPrice: 'AI Price',
            workflowMarketplace: 'Digital Marketplace',

            // Login
            loginTitle: 'Welcome back 👋',
            loginSubtitle: "Let's grow your business.",
            phoneLabel: 'Phone number',
            phonePlaceholder: '+91 98765 43210',

            // Dashboard
            goodMorning: 'Good morning',
            goodAfternoon: 'Good afternoon',
            goodEvening: 'Good evening',
            greetingSuffix: "👋",
            dashboardSubtitle: "Let's grow your business today.",
            products: 'Products',
            orders: 'Orders',
            revenue: 'Revenue',
            addNewProduct: 'Add a new product',
            addNewProductDesc: 'Create a professional listing in minutes.',
            start: 'Start',
            aiAssistant: 'Your AI Business Assistant',
            aiAssistantSuggestion: '3 of your products could use better photos.',
            improve: 'Improve',
            recentProducts: 'Recent Products',
            quickActions: 'Quick Actions',
            addProduct: 'Add Product',
            improvePhotos: 'Improve Photos',
            marketplace: 'Marketplace',

            // Products
            myProducts: 'My Products',
            published: 'Published',
            draft: 'Draft',
            duplicate: 'Duplicate',
            newest: 'Newest',
            price: 'Price',
            status: 'Status',
            all: 'All',
            noProducts: 'No products yet',
            noProductsDesc: 'Create your first digital listing.',

            // Add Product
            addProductTitle: 'Add Product',
            step1: 'Photo',
            step2: 'Describe',
            step3: 'Price',
            step4: 'Publish',
            letsStartPhoto: "Let's start with a photo",
            photoSubtitle: 'Take a clear photo of your product.',
            takePhoto: 'Take Photo',
            chooseFromGallery: 'Choose from Gallery',
            useDemoProduct: 'Use Demo Product',

            // AI Image Studio
            aiStudio: 'AI Product Studio',
            removeBackground: 'Remove Background',
            improveLighting: 'Improve Lighting',
            enhanceQuality: 'Enhance Quality',
            crop: 'Crop',
            rotate: 'Rotate',
            enhanceWithAI: 'Enhance with AI',
            useThisImage: 'Use This Image',
            tryAgain: 'Try Again',
            analyzing: 'Analyzing your product...',
            removingBg: 'Removing background...',
            improvingLight: 'Improving lighting...',
            preparingImage: 'Preparing e-commerce image...',

            // Voice Cataloger
            voiceTitle: 'Tell us about your product',
            voiceSubtitle: 'Speak naturally in your own language.',
            listening: 'Listening...',
            teluguDetected: 'Telugu detected',
            editListing: 'Edit',
            generateListing: 'Generate Listing',
            processing: 'Processing...',

            // AI Listing
            listingReady: 'Your listing is ready ✨',
            productName: 'Product Name',
            category: 'Category',
            description: 'Description',
            keywords: 'Keywords',
            languages_: 'Languages',
            regenerate: 'Regenerate',
            looksGood: 'Looks Good',

            // AI Pricing
            pricingTitle: 'Set the right price',
            pricingSubtitle: 'AI recommends a competitive selling price.',
            rawMaterialCost: 'Raw material cost',
            labourCost: 'Labour cost',
            quality: 'Quality',
            recommendedPrice: 'Recommended price',
            suggestedRange: 'Suggested range',
            competitive: 'Competitive',
            pricingExplanation: 'Based on your costs and market patterns.',
            usePrice: 'Use',
            enterManually: 'Enter Manually',

            // Preview
            previewTitle: 'Product Preview',
            material: 'Material',
            craftType: 'Craft Type',
            publishProduct: 'Publish Product',

            // Success
            successTitle: 'Your product is live! 🎉',
            successSubtitle: 'Your product can now reach buyers beyond physical exhibitions.',
            viewProduct: 'View Product',
            addAnother: 'Add Another Product',

            // Marketplace
            marketplaceTitle: 'Marketplace',
            featuredProducts: 'Featured Products',
            popularCrafts: 'Popular Crafts',
            newArrivals: 'New Arrivals',
            addToCart: 'Add to Cart',

            // Orders
            ordersTitle: 'Orders',
            pending: 'Pending',
            processing_: 'Processing',
            completed: 'Completed',
            orderReceived: 'Order received',
            shipped: 'Shipped',
            delivered: 'Delivered',

            // Order Details
            orderDetails: 'Order Details',
            buyer: 'Buyer',
            quantity: 'Quantity',
            shippingStatus: 'Shipping status',
            timeline: 'Timeline',

            // Profile
            profile: 'Profile',
            businessProfile: 'Business Profile',
            languages: 'Languages',
            notifications: 'Notifications',
            appearance: 'Appearance',
            helpSupport: 'Help & Support',
            about: 'About',
            darkMode: 'Dark Mode',

            // AI Assistant
            aiAssistantTitle: 'AI Business Assistant',
            aiChatPlaceholder: 'Ask me anything...',
            aiSuggestion1: 'Your saree listing is missing material details.',
            aiSuggestion2: 'Your product photo can be improved.',
            aiSuggestion3: '3 products have no description.',

            // Categories
            catAll: 'All',
            catTextiles: 'Textiles',
            catHandicrafts: 'Handicrafts',
            catJewellery: 'Jewellery',
            catHomeDecor: 'Home Decor',

            // Misc
            rupee: '₹',
            notifications_: 'Notifications',
            settings: 'Settings'
        },

        hi: {
            appName: 'KarigarAI',
            tagline: 'आपका AI-संचालित व्यवसाय प्रबंधक',
            loading: 'लोड हो रहा है...',
            save: 'सहेजें',
            cancel: 'रद्द करें',
            delete: 'हटाएं',
            edit: 'संपादित करें',
            back: 'वापस',
            next: 'आगे',
            done: 'हो गया',
            close: 'बंद करें',
            search: 'खोजें...',
            viewAll: 'सभी देखें',
            startSelling: 'बेचना शुरू करें',
            seeHowItWorks: 'देखें कैसे काम करता है',
            continue_: 'जारी रखें',
            continueAsDemo: 'डेमो कारीगर के रूप में जारी रखें',

            landingTitle: 'अपनी कला को डिजिटल व्यवसाय में बदलें',
            landingSubtitle: 'KarigarAI कारीगरों को पेशेवर उत्पाद लिस्टिंग बनाने, सही कीमत खोजने और ऑनलाइन खरीदारों तक पहुंचने में मदद करता है।',
            workflowPhoto: 'उत्पाद फोटो',
            workflowAI: 'AI एन्हांसमेंट',
            workflowListing: 'AI लिस्टिंग',
            workflowPrice: 'AI मूल्य',
            workflowMarketplace: 'डिजिटल मार्केटप्लेस',

            loginTitle: 'वापसी पर स्वागत है 👋',
            loginSubtitle: 'आइए अपने व्यवसाय को बढ़ाएं।',
            phoneLabel: 'फोन नंबर',
            phonePlaceholder: '+91 98765 43210',

            goodMorning: 'सुप्रभात',
            goodAfternoon: 'शुभ दोपहर',
            goodEvening: 'शुभ संध्या',
            greetingSuffix: '👋',
            dashboardSubtitle: 'आइए आज अपने व्यवसाय को बढ़ाएं।',
            products: 'उत्पाद',
            orders: 'ऑर्डर',
            revenue: 'आय',
            addNewProduct: 'नया उत्पाद जोड़ें',
            addNewProductDesc: 'मिनटों में एक पेशेवर लिस्टिंग बनाएं।',
            start: 'शुरू करें',
            aiAssistant: 'आपका AI व्यवसाय सहायक',
            aiAssistantSuggestion: 'आपके 3 उत्पादों की फोटो बेहतर हो सकती है।',
            improve: 'सुधारें',
            recentProducts: 'हाल के उत्पाद',
            quickActions: 'त्वरित कार्य',
            addProduct: 'उत्पाद जोड़ें',
            improvePhotos: 'फोटो सुधारें',
            marketplace: 'मार्केटप्लेस',

            myProducts: 'मेरे उत्पाद',
            published: 'प्रकाशित',
            draft: 'ड्राफ्ट',
            duplicate: 'डुप्लिकेट',
            newest: 'नवीनतम',
            price: 'कीमत',
            status: 'स्थिति',
            all: 'सभी',
            noProducts: 'अभी तक कोई उत्पाद नहीं',
            noProductsDesc: 'अपनी पहली डिजिटल लिस्टिंग बनाएं।',

            addProductTitle: 'उत्पाद जोड़ें',
            step1: 'फोटो',
            step2: 'विवरण',
            step3: 'कीमत',
            step4: 'प्रकाशित',
            letsStartPhoto: 'आइए फोटो से शुरू करें',
            photoSubtitle: 'अपने उत्पाद की स्पष्ट फोटो लें।',
            takePhoto: 'फोटो लें',
            chooseFromGallery: 'गैलरी से चुनें',
            useDemoProduct: 'डेमो उत्पाद का उपयोग करें',

            aiStudio: 'AI उत्पाद स्टूडियो',
            removeBackground: 'पृष्ठभूमि हटाएं',
            improveLighting: 'लाइटिंग सुधारें',
            enhanceQuality: 'गुणवत्ता बढ़ाएं',
            crop: 'क्रॉप',
            rotate: 'घुमाएं',
            enhanceWithAI: 'AI से बेहतर बनाएं',
            useThisImage: 'इस इमेज का उपयोग करें',
            tryAgain: 'फिर से कोशिश करें',
            analyzing: 'आपके उत्पाद का विश्लेषण...',
            removingBg: 'पृष्ठभूमि हटा रहे हैं...',
            improvingLight: 'लाइटिंग सुधार रहे हैं...',
            preparingImage: 'ई-कॉमर्स इमेज तैयार कर रहे हैं...',

            voiceTitle: 'हमें अपने उत्पाद के बारे में बताएं',
            voiceSubtitle: 'अपनी भाषा में स्वाभाविक रूप से बोलें।',
            listening: 'सुन रहे हैं...',
            teluguDetected: 'तेलुगु का पता चला',
            editListing: 'संपादित करें',
            generateListing: 'लिस्टिंग बनाएं',
            processing: 'प्रक्रिया हो रही है...',

            listingReady: 'आपकी लिस्टिंग तैयार है ✨',
            productName: 'उत्पाद का नाम',
            category: 'श्रेणी',
            description: 'विवरण',
            keywords: 'कीवर्ड',
            languages_: 'भाषाएं',
            regenerate: 'फिर से बनाएं',
            looksGood: 'अच्छा लग रहा है',

            pricingTitle: 'सही कीमत सेट करें',
            pricingSubtitle: 'AI एक प्रतिस्पर्धी बिक्री मूल्य की सिफारिश करता है।',
            rawMaterialCost: 'कच्चे माल की लागत',
            labourCost: 'श्रम लागत',
            quality: 'गुणवत्ता',
            recommendedPrice: 'अनुशंसित मूल्य',
            suggestedRange: 'सुझाई गई सीमा',
            competitive: 'प्रतिस्पर्धी',
            pricingExplanation: 'आपकी लागत और बाजार पैटर्न के आधार पर।',
            usePrice: 'उपयोग करें',
            enterManually: 'मैन्युअली दर्ज करें',

            previewTitle: 'उत्पाद पूर्वावलोकन',
            material: 'सामग्री',
            craftType: 'शिल्प प्रकार',
            publishProduct: 'उत्पाद प्रकाशित करें',

            successTitle: 'आपका उत्पाद लाइव है! 🎉',
            successSubtitle: 'आपका उत्पाद अब भौतिक प्रदर्शनी से परे खरीदारों तक पहुंच सकता है।',
            viewProduct: 'उत्पाद देखें',
            addAnother: 'एक और उत्पाद जोड़ें',

            marketplaceTitle: 'मार्केटप्लेस',
            featuredProducts: 'विशेष उत्पाद',
            popularCrafts: 'लोकप्रिय शिल्प',
            newArrivals: 'नए आगमन',
            addToCart: 'कार्ट में जोड़ें',

            ordersTitle: 'ऑर्डर',
            pending: 'लंबित',
            processing_: 'प्रक्रिया',
            completed: 'पूर्ण',
            orderReceived: 'ऑर्डर प्राप्त',
            shipped: 'भेज दिया',
            delivered: 'वितरित',

            orderDetails: 'ऑर्डर विवरण',
            buyer: 'खरीदार',
            quantity: 'मात्रा',
            shippingStatus: 'शिपिंग स्थिति',
            timeline: 'समयरेखा',

            profile: 'प्रोफ़ाइल',
            businessProfile: 'व्यवसाय प्रोफ़ाइल',
            languages: 'भाषाएं',
            notifications: 'सूचनाएं',
            appearance: 'दिखावट',
            helpSupport: 'सहायता और समर्थन',
            about: 'के बारे में',
            darkMode: 'डार्क मोड',

            aiAssistantTitle: 'AI व्यवसाय सहायक',
            aiChatPlaceholder: 'मुझसे कुछ भी पूछें...',
            aiSuggestion1: 'आपकी साड़ी लिस्टिंग में सामग्री विवरण गायब है।',
            aiSuggestion2: 'आपकी उत्पाद फोटो बेहतर हो सकती है।',
            aiSuggestion3: '3 उत्पादों का कोई विवरण नहीं है।',

            catAll: 'सभी',
            catTextiles: 'वस्त्र',
            catHandicrafts: 'हस्तशिल्प',
            catJewellery: 'आभूषण',
            catHomeDecor: 'घर सजावट',

            rupee: '₹',
            notifications_: 'सूचनाएं',
            settings: 'सेटिंग्स'
        },

        te: {
            appName: 'KarigarAI',
            tagline: 'మీ AI-ఆధారిత వ్యాపార నిర్వాహకుడు',
            loading: 'లోడ్ అవుతోంది...',
            save: 'సేవ్ చేయండి',
            cancel: 'రద్దు',
            delete: 'తొలగించండి',
            edit: 'సవరించండి',
            back: 'వెనుకకు',
            next: 'తదుపరి',
            done: 'పూర్తయింది',
            close: 'మూసివేయండి',
            search: 'శోధించండి...',
            viewAll: 'అన్నీ చూడండి',
            startSelling: 'అమ్మకం ప్రారంభించండి',
            seeHowItWorks: 'ఎలా పనిచేస్తుందో చూడండి',
            continue_: 'కొనసాగించండి',
            continueAsDemo: 'డెమో కారిగర్‌గా కొనసాగించండి',

            landingTitle: 'మీ కళను డిజిటల్ వ్యాపారంగా మార్చండి',
            landingSubtitle: 'KarigarAI కారిగర్‌లకు ప్రొఫెషనల్ ఉత్పత్తి లిస్టింగ్‌లు సృష్టించడంలో, సరైన ధర కనుగొనడంలో మరియు ఆన్‌లైన్ కొనుగోలుదారులను చేరుకోవడంలో సహాయపడుతుంది.',
            workflowPhoto: 'ఉత్పత్తి ఫోటో',
            workflowAI: 'AI ఎన్‌హాన్స్‌మెంట్',
            workflowListing: 'AI లిస్టింగ్',
            workflowPrice: 'AI ధర',
            workflowMarketplace: 'డిజిటల్ మార్కెట్‌ప్లేస్',

            loginTitle: 'తిరిగి స్వాగతం 👋',
            loginSubtitle: 'మీ వ్యాపారాన్ని పెంచుదాం।',
            phoneLabel: 'ఫోన్ నంబర్',
            phonePlaceholder: '+91 98765 43210',

            goodMorning: 'శుభోదయం',
            goodAfternoon: 'శుभ మధ్యాహ్నం',
            goodEvening: 'శుభ సాయంత్రం',
            greetingSuffix: '👋',
            dashboardSubtitle: 'ఈ రోజు మీ వ్యాపారాన్ని పెంచుదాం।',
            products: 'ఉత్పత్తులు',
            orders: 'ఆర్డర్లు',
            revenue: 'ఆదాయం',
            addNewProduct: 'కొత్త ఉత్పత్తి జోడించండి',
            addNewProductDesc: 'నిమిషాల్లో ప్రొఫెషనల్ లిస్టింగ్ సృష్టించండి।',
            start: 'ప్రారంభించండి',
            aiAssistant: 'మీ AI వ్యాపార సహాయకుడు',
            aiAssistantSuggestion: 'మీ 3 ఉత్పత్తుల ఫోటోలు మెరుగుపరచవచ్చు.',
            improve: 'మెరుగుపరచండి',
            recentProducts: 'ఇటీవలి ఉత్పత్తులు',
            quickActions: 'త్వరిత చర్యలు',
            addProduct: 'ఉత్పత్తి జోడించండి',
            improvePhotos: 'ఫోటోలు మెరుగుపరచండి',
            marketplace: 'మార్కెట్‌ప్లేస్',

            myProducts: 'నా ఉత్పత్తులు',
            published: 'ప్రచురించబడింది',
            draft: 'డ్రాఫ్ట్',
            duplicate: 'డూప్లికేట్',
            newest: 'కొత్త',
            price: 'ధర',
            status: 'స్థితి',
            all: 'అన్నీ',
            noProducts: 'ఇంకా ఉత్పత్తులు లేవు',
            noProductsDesc: 'మీ మొదటి డిజిటల్ లిస్టింగ్ సృష్టించండి।',

            addProductTitle: 'ఉత్పత్తి జోడించండి',
            step1: 'ఫోటో',
            step2: 'వివరణ',
            step3: 'ధర',
            step4: 'ప్రచురించు',
            letsStartPhoto: 'ఫోటోతో ప్రారంభిద్దాం',
            photoSubtitle: 'మీ ఉత్పత్తి యొక్క స్పష్టమైన ఫోటో తీయండి।',
            takePhoto: 'ఫోటో తీయండి',
            chooseFromGallery: 'గ్యాలరీ నుండి ఎంచుకోండి',
            useDemoProduct: 'డెమో ఉత్పత్తి ఉపయోగించండి',

            aiStudio: 'AI ఉత్పత్తి స్టూడియో',
            removeBackground: 'నేపథ్యం తొలగించండి',
            improveLighting: 'లైటింగ్ మెరుగుపరచండి',
            enhanceQuality: 'నాణ్యత మెరుగుపరచండి',
            crop: 'క్రాప్',
            rotate: 'తిప్పండి',
            enhanceWithAI: 'AI తో మెరుగుపరచండి',
            useThisImage: 'ఈ ఇమేజ్ ఉపయోగించండి',
            tryAgain: 'మళ్ళీ ప్రయత్నించండి',
            analyzing: 'మీ ఉత్పత్తిని విశ్లేషిస్తోంది...',
            removingBg: 'నేపథ్యం తొలగిస్తోంది...',
            improvingLight: 'లైటింగ్ మెరుగుపరుస్తోంది...',
            preparingImage: 'ఇ-కామర్స్ ఇమేజ్ సిద్ధం చేస్తోంది...',

            voiceTitle: 'మీ ఉత్పత్తి గురించి చెప్పండి',
            voiceSubtitle: 'మీ భాషలో సహజంగా మాట్లాడండి।',
            listening: 'వింటోంది...',
            teluguDetected: 'తెలుగు గుర్తించబడింది',
            editListing: 'సవరించండి',
            generateListing: 'లిస్టింగ్ సృష్టించండి',
            processing: 'ప్రాసెస్ అవుతోంది...',

            listingReady: 'మీ లిస్టింగ్ సిద్ధంగా ఉంది ✨',
            productName: 'ఉత్పత్తి పేరు',
            category: 'వర్గం',
            description: 'వివరణ',
            keywords: 'కీవర్డ్‌లు',
            languages_: 'భాషలు',
            regenerate: 'మళ్ళీ సృష్టించండి',
            looksGood: 'బాగుంది',

            pricingTitle: 'సరైన ధర సెట్ చేయండి',
            pricingSubtitle: 'AI పోటీ విక్రయ ధరను సిఫార్సు చేస్తుంది।',
            rawMaterialCost: 'ముడి సరుకు ఖర్చు',
            labourCost: 'శ్రమ ఖర్చు',
            quality: 'నాణ్యత',
            recommendedPrice: 'సిఫార్సు చేసిన ధర',
            suggestedRange: 'సూచించిన పరిధి',
            competitive: 'పోటీ',
            pricingExplanation: 'మీ ఖర్చులు మరియు మార్కెట్ నమూనాల ఆధారంగా।',
            usePrice: 'ఉపయోగించండి',
            enterManually: 'మాన్యువల్‌గా నమోదు చేయండి',

            previewTitle: 'ఉత్పత్తి ప్రివ్యూ',
            material: 'పదార్థం',
            craftType: 'కళ రకం',
            publishProduct: 'ఉత్పత్తి ప్రచురించండి',

            successTitle: 'మీ ఉత్పత్తి లైవ్‌లో ఉంది! 🎉',
            successSubtitle: 'మీ ఉత్పత్తి ఇప్పుడు భౌతిక ప్రదర్శనలకు అతీతంగా కొనుగోలుదారులను చేరుకోవచ్చు।',
            viewProduct: 'ఉత్పత్తి చూడండి',
            addAnother: 'మరొక ఉత్పత్తి జోడించండి',

            marketplaceTitle: 'మార్కెట్‌ప్లేస్',
            featuredProducts: 'ప్రత్యేక ఉత్పత్తులు',
            popularCrafts: 'ప్రసిద్ధ కళలు',
            newArrivals: 'కొత్త రాక',
            addToCart: 'కార్ట్‌కు జోడించండి',

            ordersTitle: 'ఆర్డర్లు',
            pending: 'పెండింగ్',
            processing_: 'ప్రాసెసింగ్',
            completed: 'పూర్తయింది',
            orderReceived: 'ఆర్డర్ స్వీకరించబడింది',
            shipped: 'పంపబడింది',
            delivered: 'డెలివరీ అయింది',

            orderDetails: 'ఆర్డర్ వివరాలు',
            buyer: 'కొనుగోలుదారుడు',
            quantity: 'పరిమాణం',
            shippingStatus: 'షిప్పింగ్ స్థితి',
            timeline: 'సమయరేఖ',

            profile: 'ప్రొఫైల్',
            businessProfile: 'వ్యాపార ప్రొఫైల్',
            languages: 'భాషలు',
            notifications: 'నోటిఫికేషన్లు',
            appearance: 'రూపం',
            helpSupport: 'సహాయం & మద్దతు',
            about: 'గురించి',
            darkMode: 'డార్క్ మోడ్',

            aiAssistantTitle: 'AI వ్యాపార సహాయకుడు',
            aiChatPlaceholder: 'నన్ను ఏదైనా అడగండి...',
            aiSuggestion1: 'మీ సారీ లిస్టింగ్‌లో పదార్థ వివరణ లేదు.',
            aiSuggestion2: 'మీ ఉత్పత్తి ఫోటో మెరుగుపరచవచ్చు.',
            aiSuggestion3: '3 ఉత్పత్తులకు వివరణ లేదు.',

            catAll: 'అన్నీ',
            catTextiles: 'వస్త్రాలు',
            catHandicrafts: 'హస్తశిల్పాలు',
            catJewellery: 'ఆభరణాలు',
            catHomeDecor: 'ఇంటి అలంకరణ',

            rupee: '₹',
            notifications_: 'నోటిఫికేషన్లు',
            settings: 'సెట్టింగ్‌లు'
        }
    },

    init() {
        this.currentLang = Storage.getLanguage();
    },

    t(key) {
        const lang = this.translations[this.currentLang];
        return (lang && lang[key]) || this.translations.en[key] || key;
    },

    setLanguage(lang) {
        if (this.translations[lang]) {
            this.currentLang = lang;
            Storage.setLanguage(lang);
            document.documentElement.setAttribute('lang', lang);
        }
    },

    getLanguages() {
        return [
            { code: 'en', name: 'English', native: 'English' },
            { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
            { code: 'te', name: 'Telugu', native: 'తెలుగు' }
        ];
    }
};

I18N.init();
